#!/bin/zsh
#
# Author: Joel D. Simon <jdsimon@bathymetrix.com>
# Last modified: 30-Jan-2026, Darwin Kernel Version 23.6.0

# Adjust if more MERMAID serial prefixes come onboard
for d in 452*/; do
  dir=${d:t}
  last2=${dir[-2,-1]}
  ./rdGPS "$dir" "$last2"
done
